#!/usr/bin/env bash
# Run on the server after extracting a release over the app folder (first install or update).
# Works from SSH, cPanel "Terminal", or a one-time cPanel cron job.
#
#   PHP=/opt/cpanel/ea-php84/root/usr/bin/php  (if plain `php` on the command line is not 8.4+)
#   PUBLIC_DIR=$HOME/public_html               (only if the domain cannot point to <app>/public)
#
# Steps: backup → remove files deleted in this version → cache → migrations → checks.
set -euo pipefail

APP="$(cd "$(dirname "$0")/.." && pwd)"
PHP="${PHP:-php}"
cd "$APP"
log() { echo "[$(date '+%F %T')] $*"; }

if [ ! -f .env.local ]; then
  echo "Missing $APP/.env.local — copy deploy/env.local.example to .env.local and fill it in." >&2
  exit 1
fi
"$PHP" -r 'exit(PHP_VERSION_ID >= 80401 ? 0 : 1);' || { echo "PHP 8.4.1+ required on the command line ($("$PHP" -r 'echo PHP_VERSION;')). Set PHP=/opt/cpanel/ea-php84/root/usr/bin/php" >&2; exit 1; }

log "Version $(cat VERSION 2>/dev/null || echo unknown)"

if "$PHP" bin/console dbal:run-sql -q "SELECT 1 FROM budget LIMIT 1" >/dev/null 2>&1; then
  log "Backing up before migrating"
  PHP="$PHP" "$APP/deploy/backup.sh"
fi

log "Removing files deleted in this version"
if [ -f MANIFEST ]; then
  dirs=""
  for dir in src config templates migrations vendor public/app translations bin; do
    [ -d "$dir" ] && dirs="$dirs $dir"
  done
  # Files on disk that the new release does not contain (LC_ALL=C: same sort order as the build).
  find $dirs -type f | LC_ALL=C sort | LC_ALL=C comm -23 - <(LC_ALL=C sort MANIFEST) | while read -r file; do
    rm -f "$file" && echo "  removed $file"
  done
fi

log "Refreshing cache"
rm -rf var/cache/prod
"$PHP" bin/console cache:warmup -q

log "Running database migrations"
"$PHP" bin/console doctrine:migrations:migrate -n --allow-no-migration

if [ -n "${PUBLIC_DIR:-}" ]; then
  log "Publishing web files to $PUBLIC_DIR"
  mkdir -p "$PUBLIC_DIR"
  rm -rf "$PUBLIC_DIR/app"
  cp -r public/app "$PUBLIC_DIR/app"
  cp public/.htaccess "$PUBLIC_DIR/.htaccess"
  # The web root only forwards to the real front controller, which stays outside public_html.
  printf "<?php\n// Generated by deploy/update.sh — forwards to the application outside public_html.\nreturn require '%s/public/index.php';\n" "$APP" > "$PUBLIC_DIR/index.php"
fi

log "Checking the installation"
"$PHP" bin/console app:doctor
log "Update finished"
