parameters:
    app.upload_dir: '%kernel.project_dir%/var/uploads'
    env(UPLOAD_DIR_MODE): '0750'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Application\Bus\CommandHandler:
            tags: [{ name: messenger.message_handler, bus: command.bus }]
        App\Shared\Application\Bus\EventHandler:
            tags: [{ name: messenger.message_handler, bus: event.bus }]

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/*/Domain/{Model,Event,Error}/'
            - '../src/*/UI/Http/{Input,Output}/'

when@test:
    parameters:
        app.upload_dir: '%kernel.project_dir%/var/test_uploads'
