parameters:
    app.upload_dir: '%kernel.project_dir%/var/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/*/Domain/{Model,Event,Error}/'
            - '../src/*/UI/Http/{Input,Output}/'

when@test:
    parameters:
        app.upload_dir: '%kernel.project_dir%/var/test_uploads'
