/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opens a file in the browser: for the project's Admins and Project Manager. */
        get: operations["get_api_attachments_download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/finance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balances per stage, caja menor and contingency next to the budget: for the Admins and the PM. */
        get: operations["get_api_finance_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deposits, draws and carry-overs (voided ones included), newest first. `q` searches reference and note. */
        get: operations["get_api_finance_movements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_finance_deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/contingency/draws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_finance_draw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The Admin closes a stage whose milestones are met; what is left of its money moves to the next open stage. */
        post: operations["post_api_stages_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movements/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposits and draws only, with a reason; the record stays, out of the balances. */
        post: operations["post_api_movements_void"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movements/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A proof (multipart field "file"): PDF, JPG, PNG, WEBP or HEIC up to 10 MB, checked by content. */
        post: operations["post_api_movements_attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password (session cookie). Handled by the json_login authenticator. */
        post: operations["post_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out. Intercepted by the firewall's logout listener. */
        post: operations["post_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * "Ver como": POST /api/impersonate?_switch_user=<email|_exit> is handled by the firewall (switch_user), which
         *     then redirects here without the parameter; the answer is the new current user.
         */
        get: operations["get_api_impersonate"];
        put?: never;
        /**
         * "Ver como": POST /api/impersonate?_switch_user=<email|_exit> is handled by the firewall (switch_user), which
         *     then redirects here without the parameter; the answer is the new current user.
         */
        post: operations["post_api_impersonate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_me_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users with their project roles (the users table and the "Ver como" menu), sorted by name. */
        get: operations["get_api_users_list"];
        put?: never;
        post: operations["post_api_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a user. Only the fields sent change. */
        patch: operations["patch_api_users_update"];
        trace?: never;
    };
    "/api/budget-lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_lines_update"];
        post?: never;
        delete: operations["delete_api_lines_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Only a category nothing uses. */
        delete: operations["delete_api_categories_delete"];
        options?: never;
        head?: never;
        patch: operations["patch_api_categories_rename"];
        trace?: never;
    };
    "/api/milestones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_milestones_delete"];
        options?: never;
        head?: never;
        /** While the budget is editable. Fields sent change; null clears the planned date. */
        patch: operations["patch_api_milestones_update"];
        trace?: never;
    };
    "/api/milestones/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PM or Admin, once the budget is approved. */
        post: operations["post_api_milestones_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/milestones/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin only: undoes a completion. */
        post: operations["post_api_milestones_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Any member; Team Leads get it without money. */
        get: operations["get_api_plan_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PM or Admin, also after approval. */
        post: operations["post_api_plan_categories_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_plan_stages_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/stages/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_plan_stages_order"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/budget/contingency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_plan_contingency"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/budget/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_plan_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/budget/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin only: back to the PM with what to change. */
        post: operations["post_api_plan_return"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/budget/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin only: locks the budget and activates the project. */
        post: operations["post_api_plan_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_stages_delete"];
        options?: never;
        head?: never;
        /** The name can always be fixed; planned dates only while the budget is editable. Fields sent change. */
        patch: operations["patch_api_stages_update"];
        trace?: never;
    };
    "/api/stages/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_stages_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_stages_lines_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{id}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_stages_milestones_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admins see every project; everyone else the projects they belong to. Newest first. */
        get: operations["get_api_projects_list"];
        put?: never;
        post: operations["post_api_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_projects_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin only. Only the fields sent change. */
        patch: operations["patch_api_projects_update"];
        trace?: never;
    };
    "/api/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin only. Adds a person, or changes their role if they are already in the project. */
        post: operations["post_api_projects_members_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_projects_members_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_settings_show"];
        /** Change some settings; the ones not sent stay. Admin only. */
        put: operations["put_api_settings_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable snake_case code the UI translates */
            error: string;
            violations?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        PaymentMethod: "TRANSFER" | "CASH" | "CHECK" | "OTHER";
        /** @enum {string} */
        LedgerAccount: "STAGE" | "PETTY_CASH" | "CONTINGENCY";
        AllocationInput: {
            /** @default null */
            destination: components["schemas"]["LedgerAccount"] | null;
            /**
             * Major units, e.g. "1500000.00".
             * @default
             */
            amount: string;
            /**
             * Required when the destination is STAGE.
             * @default null
             */
            stageId: number | null;
            /**
             * Optional earmark, for STAGE only.
             * @default null
             */
            categoryId: number | null;
        };
        DepositInput: {
            /**
             * YYYY-MM-DD, not in the future.
             * @default
             */
            date: string;
            /** @default null */
            method: components["schemas"]["PaymentMethod"] | null;
            /** @default null */
            reference: string | null;
            /** @default null */
            note: string | null;
            /** @default [] */
            allocations: components["schemas"]["AllocationInput"][];
        };
        DrawInput: {
            /** @default null */
            stageId: number | null;
            /**
             * Major units.
             * @default
             */
            amount: string;
            /**
             * YYYY-MM-DD, not in the future.
             * @default
             */
            date: string;
            /** @default  */
            reason: string;
        };
        CompleteStageInput: {
            /**
             * YYYY-MM-DD, not in the future nor before the stage started.
             * @default
             */
            actualEnd: string;
        };
        VoidInput: {
            /** @default  */
            reason: string;
        };
        ChangePasswordInput: {
            /** @default  */
            currentPassword: string;
            /** @default  */
            newPassword: string;
        };
        CreateUserInput: {
            /** @default  */
            email: string;
            /** @default  */
            fullName: string;
            /** @default  */
            password: string;
            /** @default false */
            admin: boolean;
            /** @default false */
            superAdmin: boolean;
        };
        UpdateUserInput: {
            /** @default null */
            email: string | null;
            /** @default null */
            fullName: string | null;
            /** @default null */
            password: string | null;
            /** @default null */
            admin: boolean | null;
            /** @default null */
            superAdmin: boolean | null;
            /** @default null */
            active: boolean | null;
        };
        LineInput: {
            /** @default 0 */
            categoryId: number;
            /** @default  */
            description: string;
            /**
             * m², m³, kg, día, global…
             * @default
             */
            unit: string;
            /**
             * Up to 3 decimals.
             * @default
             */
            quantity: string;
            /**
             * Major units, e.g. "35000.50".
             * @default
             */
            unitPrice: string;
        };
        CategoryInput: {
            /** @default  */
            name: string;
        };
        UpdateMilestoneInput: {
            /** @default null */
            name: string | null;
            /** @default null */
            weight: string | null;
            /** @default null */
            plannedDate: string | null;
        };
        CompleteMilestoneInput: {
            /**
             * YYYY-MM-DD, not in the future.
             * @default
             */
            completedAt: string;
            /** @default null */
            notes: string | null;
        };
        CreateStageInput: {
            /** @default  */
            name: string;
            /**
             * YYYY-MM-DD
             * @default null
             */
            plannedStart: string | null;
            /**
             * YYYY-MM-DD
             * @default null
             */
            plannedEnd: string | null;
        };
        ReorderInput: {
            /** @default [] */
            ids: number[];
        };
        ContingencyInput: {
            /**
             * Major units.
             * @default
             */
            contingency: string;
        };
        ReturnBudgetInput: {
            /**
             * What the PM should change.
             * @default
             */
            comment: string;
        };
        UpdateStageInput: {
            /** @default null */
            name: string | null;
            /** @default null */
            plannedStart: string | null;
            /** @default null */
            plannedEnd: string | null;
        };
        StartStageInput: {
            /**
             * YYYY-MM-DD, not in the future.
             * @default
             */
            actualStart: string;
        };
        CreateMilestoneInput: {
            /** @default  */
            name: string;
            /**
             * Percentage of the stage, e.g. "25" or "12.5".
             * @default
             */
            weight: string;
            /** @default null */
            plannedDate: string | null;
        };
        /** @enum {string} */
        ProjectStatus: "DRAFT" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
        CreateProjectInput: {
            /** @default  */
            name: string;
            /** @default null */
            description: string | null;
            /**
             * Default: the currency in Settings.
             * @default null
             */
            currency: string | null;
            /** @default null */
            status: components["schemas"]["ProjectStatus"] | null;
            /**
             * YYYY-MM-DD
             * @default null
             */
            plannedStart: string | null;
            /**
             * YYYY-MM-DD
             * @default null
             */
            plannedEnd: string | null;
        };
        UpdateProjectInput: {
            /** @default null */
            name: string | null;
            /** @default null */
            description: string | null;
            /** @default null */
            currency: string | null;
            /** @default null */
            status: components["schemas"]["ProjectStatus"] | null;
            /** @default null */
            plannedStart: string | null;
            /** @default null */
            plannedEnd: string | null;
        };
        /** @enum {string} */
        ProjectRole: "PROJECT_MANAGER" | "TEAM_LEAD";
        MemberInput: {
            /** @default 0 */
            userId: number;
            /** @default null */
            role: components["schemas"]["ProjectRole"] | null;
        };
        SettingsInput: {
            /** @default null */
            defaultCurrency: string | null;
            /** @default null */
            teamLeadExpenseLimit: string | null;
            /** @default null */
            pettyCashLowBalancePercent: number | null;
            /** @default null */
            budgetWarningPercents: number[] | null;
        };
        FinancePermissionsOutput: {
            deposit: boolean;
            void: boolean;
            drawContingency: boolean;
            completeStages: boolean;
        };
        FinanceTotalsOutput: {
            /** Stages plus contingency. */
            budget: string;
            deposited: string;
            spent: string;
            stagesAvailable: string;
            pettyCash: string;
            contingency: string;
        };
        StageFundingOutput: {
            id: number;
            name: string;
            /** @enum {string} */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
            budget: string;
            deposited: string;
            contingencyDraws: string;
            carriedIn: string;
            carriedOut: string;
            /** Deposited + draws + carried in. */
            received: string;
            available: string;
            /** Received above the budget. */
            beyondBudget: string;
            spent: string;
            remainingBudget: string;
            /** Basis points of the budget spent (can pass 10000). */
            executed: number;
            /** Basis points of the budget received (can pass 10000). */
            funded: number;
            /** Where its leftover goes when completed; null when completed or last. */
            nextStage?: string | null;
        };
        CategorySpendingOutput: {
            id: number;
            name: string;
            /** Major units. */
            budget: string;
            /** Major units. */
            spent: string;
            /** Basis points of the budget spent. */
            executed: number;
        };
        ContingencyOutput: {
            budgeted: string;
            deposited: string;
            /** Leftover of the last stage. */
            carriedIn: string;
            drawn: string;
            balance: string;
        };
        PettyCashSummaryOutput: {
            deposited: string;
            balance: string;
        };
        FinanceOutput: {
            currency: string;
            budgetApproved: boolean;
            permissions: components["schemas"]["FinancePermissionsOutput"];
            totals: components["schemas"]["FinanceTotalsOutput"];
            stages: components["schemas"]["StageFundingOutput"][];
            categories: components["schemas"]["CategorySpendingOutput"][];
            contingency: components["schemas"]["ContingencyOutput"];
            pettyCash: components["schemas"]["PettyCashSummaryOutput"];
        };
        FinancePersonOutput: {
            id: number;
            fullName: string;
        };
        VoidOutput: {
            /** Format: date-time */
            at: string;
            by: string;
            reason: string;
        };
        LedgerEntryOutput: {
            /** @enum {string} */
            account: "STAGE" | "PETTY_CASH" | "CONTINGENCY";
            stageId?: number | null;
            stageName?: string | null;
            categoryId?: number | null;
            categoryName?: string | null;
            /** Major units, signed: negative when the account gives money. */
            amount: string;
        };
        AttachmentOutput: {
            id: number;
            name: string;
            mimeType: string;
            size: number;
        };
        MovementOutput: {
            id: number;
            /** @enum {string} */
            type: "DEPOSIT" | "CONTINGENCY_DRAW" | "CARRYOVER" | "EXPENSE" | "REIMBURSEMENT";
            /** Format: date */
            date: string;
            /** Major units, positive. */
            amount: string;
            /** @enum {string|null} */
            method?: "TRANSFER" | "CASH" | "CHECK" | "OTHER" | null;
            reference?: string | null;
            note?: string | null;
            createdBy: components["schemas"]["FinancePersonOutput"];
            /** Format: date-time */
            createdAt: string;
            voided?: components["schemas"]["VoidOutput"] | null;
            entries: components["schemas"]["LedgerEntryOutput"][];
            attachments: components["schemas"]["AttachmentOutput"][];
        };
        MovementPageOutput: {
            items: components["schemas"]["MovementOutput"][];
            total: number;
            page: number;
            perPage: number;
        };
        MembershipOutput: {
            projectId: number;
            projectName: string;
            /** @enum {string} */
            role: "PROJECT_MANAGER" | "TEAM_LEAD";
        };
        ImpersonatorOutput: {
            id: number;
            fullName: string;
        };
        CurrentUserOutput: {
            id: number;
            email: string;
            fullName: string;
            admin: boolean;
            superAdmin: boolean;
            memberships: components["schemas"]["MembershipOutput"][];
            /** Set while a super admin is viewing the app as this user. */
            impersonator?: components["schemas"]["ImpersonatorOutput"] | null;
            /** Shows the "Ver como" menu: a super admin, or someone being viewed as (to offer the way back). */
            canImpersonate: boolean;
        };
        UserOutput: {
            id: number;
            email: string;
            fullName: string;
            admin: boolean;
            superAdmin: boolean;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            memberships: components["schemas"]["MembershipOutput"][];
        };
        UserPageOutput: {
            items: components["schemas"]["UserOutput"][];
            total: number;
            page: number;
            perPage: number;
        };
        PlanProjectOutput: {
            id: number;
            name: string;
            currency: string;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
        };
        PlanPermissionsOutput: {
            /** Amounts are shown (PM and Admin). */
            viewFinancials: boolean;
            /** Stages, lines, milestones and contingency can be edited (the budget is a draft or was returned). */
            edit: boolean;
            /** Categories can be added and renamed (also after approval). */
            manageCategories: boolean;
            submit: boolean;
            /** The Admin may approve or return it (it is submitted). */
            review: boolean;
            /** Stages can be started and milestones met (the budget is approved). */
            track: boolean;
            reopenMilestones: boolean;
        };
        PersonOutput: {
            id: number;
            fullName: string;
        };
        MilestoneOutput: {
            id: number;
            name: string;
            /** Basis points of the stage (10000 = 100 %) */
            weight: number;
            /** Format: date */
            plannedDate?: string | null;
            /** Format: date */
            completedAt?: string | null;
            completedBy?: components["schemas"]["PersonOutput"] | null;
            completionNotes?: string | null;
            /** Not met and its planned date has gone by */
            overdue: boolean;
        };
        LineOutput: {
            id: number;
            categoryId: number;
            description: string;
            unit: string;
            /** "12.5" */
            quantity: string;
            /** Major units */
            unitPrice: string;
            /** Major units: quantity × unit price, rounded half up */
            total: string;
        };
        StageOutput: {
            id: number;
            name: string;
            position: number;
            /** @enum {string} */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
            /** Format: date */
            plannedStart?: string | null;
            /** Format: date */
            plannedEnd?: string | null;
            /** Format: date */
            actualStart?: string | null;
            /** Format: date */
            actualEnd?: string | null;
            /** Basis points met */
            progress: number;
            /** Basis points: must be 10000 to submit */
            milestoneWeightTotal: number;
            milestones: components["schemas"]["MilestoneOutput"][];
            /** Major units; null for Team Leads */
            budgetTotal?: string | null;
            /** Share of the budget in basis points; null for Team Leads */
            weight?: number | null;
            /** null for Team Leads */
            lines?: components["schemas"]["LineOutput"][] | null;
        };
        CategoryOutput: {
            id: number;
            name: string;
        };
        CategoryTotalOutput: {
            categoryId: number;
            /** Major units budgeted in the category */
            total: string;
        };
        BudgetEventOutput: {
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "RETURNED" | "APPROVED";
            user: components["schemas"]["PersonOutput"];
            comment?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        BudgetOutput: {
            contingency: string;
            /** Sum of the stages (contingency excluded) */
            stagesTotal: string;
            total: string;
            /** Format: date-time */
            approvedAt?: string | null;
            byCategory: components["schemas"]["CategoryTotalOutput"][];
            events: components["schemas"]["BudgetEventOutput"][];
        };
        PlanIssueOutput: {
            /** @enum {string} */
            code: "no_stages" | "stage_without_lines" | "milestone_weights";
            stageId?: number | null;
        };
        PlanOutput: {
            project: components["schemas"]["PlanProjectOutput"];
            permissions: components["schemas"]["PlanPermissionsOutput"];
            /** @enum {string} */
            budgetStatus: "DRAFT" | "SUBMITTED" | "RETURNED" | "APPROVED";
            /** Project progress: stages weighted by their share of the budget */
            progress: number;
            stages: components["schemas"]["StageOutput"][];
            categories: components["schemas"]["CategoryOutput"][];
            /** null for Team Leads */
            budget?: components["schemas"]["BudgetOutput"] | null;
            /** What blocks submitting, while editable; null for Team Leads */
            issues?: components["schemas"]["PlanIssueOutput"][] | null;
        };
        MemberUserOutput: {
            id: number;
            email: string;
            fullName: string;
        };
        MemberOutput: {
            id: number;
            role: components["schemas"]["ProjectRole"];
            user: components["schemas"]["MemberUserOutput"];
        };
        ProjectOutput: {
            id: number;
            name: string;
            description?: string | null;
            currency: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * YYYY-MM-DD
             * Format: date
             */
            plannedStart?: string | null;
            /**
             * YYYY-MM-DD
             * Format: date
             */
            plannedEnd?: string | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * The signed-in user's role here: ADMIN (global), PROJECT_MANAGER or TEAM_LEAD
             * @enum {string}
             */
            myRole: "ADMIN" | "PROJECT_MANAGER" | "TEAM_LEAD";
            members: components["schemas"]["MemberOutput"][];
        };
        ProjectPageOutput: {
            items: components["schemas"]["ProjectOutput"][];
            total: number;
            page: number;
            perPage: number;
        };
        SettingsOutput: {
            /** ISO 4217 code for new projects */
            defaultCurrency: string;
            /** Major units; a Team Lead expense above it also needs an Admin's approval */
            teamLeadExpenseLimit: string;
            /** Caja menor alert when the balance drops below this % of the last top-up */
            pettyCashLowBalancePercent: number;
            /** Budget alert thresholds, % of a stage or category budget, ascending */
            budgetWarningPercents: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_attachments_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file, inline, with its stored type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description forbidden (Team Leads) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description attachment_not_found, file_missing, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_finance_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The funding summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceOutput"];
                };
            };
            /** @description forbidden: Team Leads see no money; only Admins move it */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found (also outside the project), stage_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_finance_movements: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of movements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementPageOutput"];
                };
            };
            /** @description forbidden: Team Leads see no money; only Admins move it */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found (also outside the project), stage_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_finance_deposit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositInput"];
            };
        };
        responses: {
            /** @description The deposit */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementOutput"];
                };
            };
            /** @description forbidden: Team Leads see no money; only Admins move it */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found (also outside the project), stage_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_not_approved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed (fields such as allocations[1].stageId) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_finance_draw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrawInput"];
            };
        };
        responses: {
            /** @description The draw */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementOutput"];
                };
            };
            /** @description forbidden: Team Leads see no money; only Admins move it */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found (also outside the project), stage_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_not_approved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed (amount above the contingency balance, stage completed) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_stages_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteStageInput"];
            };
        };
        responses: {
            /** @description The refreshed funding summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceOutput"];
                };
            };
            /** @description forbidden: Team Leads see no money; only Admins move it */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found (also outside the project), stage_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_not_approved, stage_not_in_progress, stage_milestones_pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_movements_void: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidInput"];
            };
        };
        responses: {
            /** @description The voided movement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementOutput"];
                };
            };
            /** @description forbidden: Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description movement_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description movement_not_voidable, movement_already_voided, void_would_overdraw, cycle_closed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_movements_attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The movement with its files */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementOutput"];
                };
            };
            /** @description forbidden: Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description movement_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed on "file" */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOutput"];
                };
            };
            /** @description invalid_credentials, account_disabled or too_many_attempts */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOutput"];
                };
            };
        };
    };
    get_api_impersonate: {
        parameters: {
            query?: {
                /** @description Email of the user to view as, or _exit */
                _switch_user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user now signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOutput"];
                };
            };
            /** @description Switched; follow to GET /api/impersonate */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description switch_user_not_allowed, or not allowed to view as that user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_impersonate: {
        parameters: {
            query?: {
                /** @description Email of the user to view as, or _exit */
                _switch_user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user now signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOutput"];
                };
            };
            /** @description Switched; follow to GET /api/impersonate */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description switch_user_not_allowed, or not allowed to view as that user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_me_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed (currentPassword wrong, newPassword too short or unchanged) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_users_list: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageOutput"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInput"];
            };
        };
        responses: {
            /** @description The new user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed or email_taken */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patch_api_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInput"];
            };
        };
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description user_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed, email_taken or cannot_change_own_access */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    put_api_lines_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_api_lines_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_api_categories_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description category_in_use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patch_api_categories_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
        };
    };
    delete_api_milestones_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked, budget_not_approved, milestone_already_completed, stage_completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patch_api_milestones_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMilestoneInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked, budget_not_approved, milestone_already_completed, stage_completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_milestones_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteMilestoneInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked, budget_not_approved, milestone_already_completed, stage_completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_milestones_reopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description budget_locked, budget_not_approved, milestone_already_completed, stage_completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_plan_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_plan_categories_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed (name taken) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_plan_stages_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStageInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    put_api_plan_stages_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed: ids must be every stage once */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    put_api_plan_contingency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContingencyInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_plan_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_incomplete, with `issues` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_plan_return: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnBudgetInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_not_submitted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_plan_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description project_not_found (also when not a member) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_api_stages_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description stage_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked, budget_not_approved, stage_already_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patch_api_stages_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStageInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description stage_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked, budget_not_approved, stage_already_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_stages_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartStageInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description stage_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked, budget_not_approved, stage_already_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_stages_lines_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description stage_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked, budget_not_approved, stage_already_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_stages_milestones_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMilestoneInput"];
            };
        };
        responses: {
            /** @description The refreshed plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOutput"];
                };
            };
            /** @description stage_not_found, or project_not_found outside the project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description budget_locked, budget_not_approved, stage_already_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_projects_list: {
        parameters: {
            query?: {
                q?: string | null;
                status?: unknown;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPageOutput"];
                };
            };
        };
    };
    post_api_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description The new project (DRAFT) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOutput"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_projects_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project with its members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOutput"];
                };
            };
            /** @description project_not_found (also when the user is not in it) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patch_api_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInput"];
            };
        };
        responses: {
            /** @description The project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOutput"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description project_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed or currency_locked */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_api_projects_members_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInput"];
            };
        };
        responses: {
            /** @description The project with its members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOutput"];
                };
            };
            /** @description project_manager_exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description user_not_found, admin_is_global, user_inactive or validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    delete_api_projects_members_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description project_not_found or member_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_api_settings_show: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The global settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOutput"];
                };
            };
        };
    };
    put_api_settings_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description The global settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOutput"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
